# This is a basic workflow to help you get started with Actions

name: build-windows

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:      
      - uses: actions/checkout@v3
        with:
          repository: wireshark/wireshark
      - name: Install Qt6
        uses: jurplel/install-qt-action@v3.1.0
        with:
          version: 6.2.1
          # install os; linux, windows, or mac
          os: windows
          # what platform are you installing for? desktop, winrt, android, or ios
          platform: desktop    
